# -*- coding: utf-8 -*-
"""brain_tumor_classification_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_txTDSOAalm0Hl6MzBudlZCnWiHRh3q
"""

import streamlit as st
from joblib import load
import numpy as np
from PIL import Image

# Load the model
model = load('brain_tumor_classification_model.joblib')

# Streamlit app
st.title('Brain Tumor Classification')
uploaded_file = st.file_uploader("Upload an MRI image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Read and preprocess the image
    img = np.array(Image.open(uploaded_file))
    st.image(img, caption='Uploaded MRI Image.', use_column_width=True)

    # Ensure the image is preprocessed correctly for the model
    # Example: Reshape the image to match the model's expected input
    img_resized = img.reshape(1, -1)  # Adjust based on your model's requirements

    # Make predictions using the model
    try:
        result = model.predict(img_resized)
        st.write('Prediction:', result[0])  # Display the predicted result
    except Exception as e:
        st.error(f"Error during prediction: {e}")